### PR TITLE
Fix deprecated rule warnings, update dependencies, commit lockfile.

### PR DESCRIPTION
**Pull request by mattheu**
Running this locally I was hitting some warnings due to a rule having been deprecated. 

Needs bot stylelint and wordpress stylelint rules to be updated as well.

### CODE REVIEW

**Comment by tfrommen** [comment]
This is captured in #231. The "problem" that I see with this change is that it's a breaking change. If we want to do this, then it needs to be a major version release.
Other than that, the change makes sense, of course. 🙂

**Comment by mattheu** [comment]
Good point and happy to hold off on it just eager to get rid of the notices :)

**Comment by tfrommen** [comment]
Looking at #248, I guess this one here can now be closed, @ntwb? 🙂

**Comment by tfrommen** [comment]
Closing in favor of #248.

**Pull request closed without merging**
