### PR TITLE
incorrectly detects `function() use () {}`

### PR DESCRIPTION
**Pull request by roborourke**
If you have a nested or lambda function using the `use` keyword this sniff picks it up and flags it as an issue.

In the above scenario the token will have `nested_parenthesis` set so this PR just adds a check for that and skips the token.

### CODE REVIEW

**Comment by grappler** [comment]
It may be good to add a test for it too.

**Comment by roborourke** [comment]
Didn't spot the test suite 😳

**Comment by roborourke** [comment]
@grappler so I don't think any of this is tested at the moment, not sure how to do it for code sniffer libraries yet

**Comment by grappler** [comment]
Ah, yes. :(

It is not that difficult. The folder structure is 
- HM
  - Tests
    - Layout
      - OrderUnitTest.inc (This contains the test code)
      - OrderUnitTest.php (This tells the test in which line the code is bad.) You can see an example here. https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Tests/Arrays/ArrayKeySpacingRestrictionsUnitTest.php

As there is no Travis set up you would need to manually test it. Documentation https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/CONTRIBUTING.md#unit-testing

**Comment by roborourke** [comment]
@grappler I hit a snag when I was trying to do this yesterday, code sniffer is required downstream as a dependency however the tests directory isn't part of the package. How do you get around it on wpcs?

**Comment by grappler** [comment]
I am not sure I understood you correctly.  This is how you would install phpunit in phpcs.

```
which phpcs
cd /path/to/phpcs
composer install
vendor/bin/phpunit --filter WordPress tests/AllTests.php
```

If you have phpunit installed elsewhere then you could just run
`phpunit --filter WordPress /path/to/phpcs/tests/AllTests.php`

**Comment by roborourke** [comment]
@grappler ohhh, the `cd` into phpcs bit was what I was missing. Let me try that

**Comment by roborourke** [comment]
Also I need a clone of phpcs right?

**Comment by grappler** [comment]
You should have phpcs on your system otherwise the sniffing would not work. It depends on how you have installed it. It will not work if you have installed it as phar.

**Comment by roborourke** [comment]
I think I installed via brew originally. I've cloned the repo and set up my path to use that but currently it doesn't seem to be saving the installed paths in it's config :/

**Comment by grappler** [comment]
I think the reason is due to how the paths are defined in the `ruleset` https://github.com/humanmade/coding-standards/issues/2

**Comment by roborourke** [comment]
@rmccue can you take a gander at this when you get some time? Need to test the paths still work when using it in a project actually. Anyway, have a play with the tests, I added docs on running them to the readme.

- [ ] TODO: create a docker image with php, git, composer & phpcs already checked out and this will super fast

**Comment by rmccue** [comment]
@roborourke FWIW, I'd rather see the test suite in a separate PR (although you can add the test cases in this one if you want).

Not sure if Circle supports it, but Travis supports caching Composer dependencies and stuff pretty easily. (I'd also rather we use Travis than Circle for open source stuff generally, but I don't care that much, and you've already written it.)

If you want to split the unrelated changes into a separate PR, happy to merge the `use` change straight away.

**Comment by roborourke** [comment]
@rmccue that's interesting, I thought we were settling on circle as a company! I'll make a new PR for the `use` changes so it's clean.

**Comment by roborourke** [comment]
Closed in favour of #8 and #9

**Pull request closed without merging**
