### PR TITLE
Add typescript documentation

### PR DESCRIPTION
**Pull request by nathanielks**
Nothing much else to say! Out of the box, the eslint package will mostly work fine, but it will throw errors some TypeScript-specific syntax. This fixes that!

### CODE REVIEW

**Comment by nathanielks** [comment]
Aw, damn:
```
Failed to run hmlinter
Could not run: Error: Cannot find module '@typescript-eslint/parser'
```

Is there a way we can have hmlinter install linter dependencies?

**Comment by pdewouters** [comment]
@nathanielks I believe you can make a PR to add them here to our `eslint-config-humanmade` packages

**Comment by kadamwhite** [comment]
@nathanielks The docs look good; lookin at your "Oh, Damn", do you mean that it still doesn't work if you install that package, as you documented?

**Comment by nathanielks** [comment]
@kadamwhite it's been so long I don't recall 🙈 I did some local testing and I cannot reproduce the issue, but if I do I'll follow up with another PR 👍

**Pull request merged**
