### PR TITLE
Allow $namespace.php in function files

### PR DESCRIPTION
**Pull request by joehoyle**
See https://github.com/humanmade/coding-standards/issues/89

Needs some tests too, putting here as a first pass.

### CODE REVIEW

**Comment by mikeselander** [comment]
FYI https://github.com/humanmade/coding-standards/blob/master/HM/Sniffs/Files/NamespaceDirectoryNameSniff.php#L86 will also need to be updated as it will push for a `/directory/namespace.php` in the logic and complain if you're in a subdirectory off of `/inc` and have a non-standards file name.

For example:
`/inc/my-custom-namespace` -> passes due to a short circuit in the code
`/inc/my-custom-namespace.php` -> passes
`/inc/bananas/my-custom-namespace.php` -> fails

**Comment by joehoyle** [comment]
👍

**Comment by mikeselander** [comment]
@joehoyle do you think you'll have time to finish this up over the next few weeks or should someone else pick this up?

**Comment by joehoyle** [comment]
I'm pretty busy with the Altis version 1 timeline, if anyone else has time to pick this up within the next month, please go ahead :)

**Comment by mikeselander** [comment]
@rmccue this is ready for a review, would appreciate you eyes on this 🙏

**Pull request merged**
