### PR TITLE
Allow json_encode / json_decode

### PR DESCRIPTION
**Pull request by joehoyle**
Given we have PHP 7+, we don't need to use wp_json_encode / wp_json_decode. Using the WP alternatives is also not easy in things like SUNRISE or wp-config.php as those functions may not be yet available.

### CODE REVIEW

**Comment by rmccue** [comment]
Hmm, I'd probably leave this one; `wp_json_encode` does sanity checking on the UTF-8 encoding of strings, so probably good to keep that?

**Comment by joehoyle** [comment]
@rmccue I think using it is probably still ok, but I'm not sure we should be disallowing the internal PHP functions.

**Comment by roborourke** [comment]
There are now cases where our coding standards should apply that are either not in the WP context or too early in the WP bootstrapping process for this to be possible.

**Comment by kadamwhite** [comment]
@joehoyle @roborourke If one of you can fix the merge conflict, we'll get this landed

**Comment by kadamwhite** [comment]
Went ahead and cleaned that up myself; some of the other PR's were confusing Git's normal merge algorithm something fierce. Will land once checks pass.

**Pull request merged**
